//stateful containers that will update presentational componenets


// STATES FOR CARD DISPLAY WILL BE HERE

// IT WILL RETURN DIVS THAT INCLUDE ALL OF THE CARDS THAT CARD DISPLAY CREATES

// IT WILL PASS DOWN THE CARD ID, WORD, AND DEFINITION AS PROPS